#include "board.h"
#include <hal.h>

/*
 * Early initialization code.
 * This initialization must be performed just after stack setup and before
 * any other initialization.
 */
void __chibios_override___early_init(void) {
}

/*
 * Board-specific initialization code.
 */
void __chibios_override_boardInit(void) {

    /* USB */
    palSetLineMode(USBVBUS, MODE_FUNC_ALT1 | MODE_MODE_PULL_UP | MODE_AD_DIGITAL);
    palSetLineMode(USBCONN, MODE_FUNC_ALT1);

    /* ROWS */
    palSetLineMode(PAL_LINE(IOPORT1,  0), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  1), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  2), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  3), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  4), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  5), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  6), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  7), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  8), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);
    palSetLineMode(PAL_LINE(IOPORT1,  9), MODE_DIR_IN | MODE_AD_DIGITAL | MODE_MODE_PULL_UP);

    /* COLS */
    palSetLineMode(PAL_LINE(IOPORT1, 12), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 13), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 14), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 15), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 16), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 17), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 18), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 19), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 20), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 21), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 22), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
    palSetLineMode(PAL_LINE(IOPORT1, 23), MODE_DIR_OUT | MODE_AD_DIGITAL | MODE_MODE_INACTIVE);
}
